name: reminder_app
description: reminder app for all purpose

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#used packages in app
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  get_it: ^7.2.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  intl: ^0.17.0
  simple_animations:
  flutter_local_notifications: 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
